config/routes.rb
Rails.application.routes.draw do
  resources :pizza_pies

  root 'users#landing'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/pizza_py.rb
class PizzaPy < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pizza_pies_controller.rb
class PizzaPiesController < ApplicationController
  before_action :set_pizza_py, only: [:show, :edit, :update, :destroy]

  # GET /pizza_pies
  # GET /pizza_pies.json
  def index
    @pizza_pies = PizzaPy.all
  end

  # GET /pizza_pies/1
  # GET /pizza_pies/1.json
  def show
  end

  # GET /pizza_pies/new
  def new
    @pizza_py = PizzaPy.new
  end

  # GET /pizza_pies/1/edit
  def edit
  end

  # POST /pizza_pies
  # POST /pizza_pies.json
  def create
    @pizza_py = PizzaPy.new(pizza_py_params)

    respond_to do |format|
      if @pizza_py.save
        format.html { redirect_to @pizza_py, notice: 'Pizza py was successfully created.' }
        format.json { render :show, status: :created, location: @pizza_py }
      else
        format.html { render :new }
        format.json { render json: @pizza_py.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pizza_pies/1
  # PATCH/PUT /pizza_pies/1.json
  def update
    respond_to do |format|
      if @pizza_py.update(pizza_py_params)
        format.html { redirect_to @pizza_py, notice: 'Pizza py was successfully updated.' }
        format.json { render :show, status: :ok, location: @pizza_py }
      else
        format.html { render :edit }
        format.json { render json: @pizza_py.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pizza_pies/1
  # DELETE /pizza_pies/1.json
  def destroy
    @pizza_py.destroy
    respond_to do |format|
      format.html { redirect_to pizza_pies_url, notice: 'Pizza py was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pizza_py
      @pizza_py = PizzaPy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pizza_py_params
      params.fetch(:pizza_py, {})
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/pizza_pies/index'
    else
      # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def home
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pizza_pies_helper.rb
module PizzaPiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PeopleSeekingPizza</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</body>
</html>

app/views/pizza_pies/_form.html.erb
<%= form_for(@pizza_py) do |f| %>
  <% if @pizza_py.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pizza_py.errors.count, "error") %> prohibited this pizza_py from being saved:</h2>

      <ul>
      <% @pizza_py.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pizza_pies/edit.html.erb
<h1>Editing Pizza Py</h1>

<%= render 'form' %>

<%= link_to 'Show', @pizza_py %> |
<%= link_to 'Back', pizza_pies_path %>

app/views/pizza_pies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pizza Pies</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pizza_pies.each do |pizza_py| %>
      <tr>
        <td><%= link_to 'Show', pizza_py %></td>
        <td><%= link_to 'Edit', edit_pizza_py_path(pizza_py) %></td>
        <td><%= link_to 'Destroy', pizza_py, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pizza py', new_pizza_py_path %>

app/views/pizza_pies/new.html.erb
<h1>New Pizza Py</h1>

<%= render 'form' %>

<%= link_to 'Back', pizza_pies_path %>

app/views/pizza_pies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_pizza_py_path(@pizza_py) %> |
<%= link_to 'Back', pizza_pies_path %>

app/views/users/home.html.erb
<h1> Users Home Page! </h1>

app/views/users/landing.html.erb
<div class="background_image">
  <div class="home_page_container">
    <h1 class="home_header text-center"><strong> Welcome to People Seeking Pizza </strong></h1>
    <h2 class="home_header text-center"><strong> Bringing the power of pizza to the people since 2016! </strong></h2>
    <div class="btn-group" role="group" aria-label="...">
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".login-modal">
        <p>Login</p><!-- <%= link_to "Login", login_path %> -->
      </button>
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".signup-modal">
        <p>Signup</p>
      </button>
    </div>
  </div>
  <!-- Signup Modal -->
  <div class="modal fade signup-modal" tabindex="-1" role="dialog" aria-labelledby="mySignupModal">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <h1>Signup!</h1>

        <%= form_for :user, url: '/users' do |f| %>

        Name: <%= f.text_field :name %>
        Email: <%= f.text_field :email %>
        Password: <%= f.password_field :password %>
        Password Confirmation: <%= f.password_field :password_confirmation %>
        <%= f.submit "Submit" %>

        <% end %>
      </div>
    </div>
  </div>
  <!-- Login Modal -->
  <div class="modal fade login-modal" tabindex="-1" role="dialog" aria-labelledby="myLoginModal">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <h1>Login</h1>

        <%= form_tag '/login' do %>

        Email: <%= text_field_tag :email %>
        Password: <%= password_field_tag :password %>
        <%= submit_tag "Submit" %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>
  <button type="button" class="btn btn-primary" id="login_button"><%= link_to "Login", login_path %></button>

<% end %>